name: Python autotests

on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      -name: Checkout autotests
       uses: actions/checkout@v4
      -name: set up Python environment
       uese: actions/setup-python@v5
       with:
         python-version: '3.13'
       name: Install dependecies
       run: pip install -r requirements.txt
       name: run tests
       run: pytest
      
       
