name: Python autotests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests set
        required: true
        type: choice
        default: smoke
        options: 
          - smoke
          - regression
          - extended
          - all
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
        
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependecies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps
             
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results

      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
   
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results

      - name: run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended --alluredir=allure-results

      - name: Install Java
        uses: actions/setup-Java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
          tar -zxvf allure-2.24.1.tgz
          sudo mv allure-2.24.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate report
        run: allure generate -c allure-results -o _site

      - name: Save allure report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 10
          
  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
           
         
          
